export const dateSliderDates = [
  { day: "Mon", dateNumber: 1, id: 1 },
  { day: "Tue", dateNumber: 2, id: 2 },
  { day: "Wed", dateNumber: 3, id: 3 },
  { day: "Thu", dateNumber: 4, id: 4 },
  { day: "Fri", dateNumber: 5, id: 5 },
  { day: "Sat", dateNumber: 6, id: 6 },
  { day: "Sun", dateNumber: 7, id: 7 },
  { day: "Mon", dateNumber: 8, id: 8 },
  { day: "Tue", dateNumber: 9, id: 9 },
  { day: "Wed", dateNumber: 10, id: 10 },
  { day: "Thu", dateNumber: 11, id: 11 },
  { day: "Fri", dateNumber: 12, id: 12 },
];

export const dateSliderBreakPoints = {
  190: {
    slidesPerView: 2,
    spaceBetween: 20,
  },
  260: {
    slidesPerView: 3,
    spaceBetween: 20,
  },
  360: {
    slidesPerView: 4,
    spaceBetween: 20,
  },
  458: {
    slidesPerView: 5,
    spaceBetween: 20,
  },
  640: {
    slidesPerView: 5,
    spaceBetween: 20,
  },
  768: {
    slidesPerView: 5,
    spaceBetween: 20,
  },
  850: {
    slidesPerView: 6,
    spaceBetween: 20,
  },
  1240: {
    slidesPerView: 8,
    spaceBetween: 20,
  },
};

export const allAvailableTasks = [
  {
    id: 1,
    title: "Create Wireframe",
    startTime: new Date(),
    endTime: new Date(),
    done: false,
  },
  {
    id: 2,
    title: "Go shopping",
    startTime: new Date(),
    endTime: new Date(),
    done: false,
  },
  {
    id: 3,
    title: "Go shopping",
    startTime: new Date(),
    endTime: new Date(),
    done: true,
  },
  {
    id: 4,
    title: "Go shopping",
    startTime: new Date(),
    endTime: new Date(),
    done: true,
  },
  {
    id: 5,
    title: "Go shopping",
    startTime: new Date(),
    endTime: new Date(),
    done: true,
  },
  {
    id: 6,
    title: "Go shopping",
    startTime: new Date(),
    endTime: new Date(),
    done: true,
  },
  {
    id: 7,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 8,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 9,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 10,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 11,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 12,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 13,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 14,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 15,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 16,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 17,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 18,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 19,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 20,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 21,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 22,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 23,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 24,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 25,
    title: "Go shopping",
    startTime: new Date("2023-09-25"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 26,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 27,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 28,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 29,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 30,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 31,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 32,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 33,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 34,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 35,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 36,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 37,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 38,
    title: "Go shopping",
    startTime: new Date("2023-09-20"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 39,
    title: "Go shopping",
    startTime: new Date("2023-09-06"),
    endTime: new Date(),
    done: true,
  },
  {
    id: 40,
    title: "Go shopping",
    startTime: new Date("2023-09-05"),
    endTime: new Date(),
    done: true,
  },
];
